config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :employees do
    member do
      patch :cancel_edit
      post :edit
      post :new
    end
  end

  resources :sales, only: :index

  resource :dashboard, except: %i[index new create edit update destroy] do
    member do
      get :revenue
      get :orders
    end
  end

  root "employees#index"
end

app/models/employee.rb
# frozen_string_literal: true

# https://viblo.asia/p/rails-full-text-search-with-sqlite-OeVKBvvEKkW
# https://www.sqlite.org/fts3.html
# https://www.sqlite.org/fts5.html
# https://www.sqlitetutorial.net/sqlite-full-text-search/
# https://zarko-gajic.iz.hr/sqlite-referential-integrity-with-full-text-search-virtual-tables-used-in-a-delphi-application/
# https://www.speich.net/articles/en/2020/07/03/sqlite-fts4-standard-vs-enhanced-query-syntax/
class Employee < ApplicationRecord
  include Sqlite3Indexer
  include Sqlite3SafeMethods

  belongs_to :company

  # reset the cache when the model changes (you may omit the callbacks if your DB is static)
  after_create  { self.class.clear_cache }
  after_destroy { self.class.clear_cache }

  class << self
    def build_search(options = {})
      query = options.fetch(:query, nil)

      return all unless query.present?

      match = ActiveModel::Type::Boolean.new.cast(options[:match])

      return search_by_match(query) if match

      search_by_like(query)
    end

    def async_count
      async_count_by_sql("SELECT COUNT(*) FROM #{table_name}").value
    end

    def cache
      @cache ||= {}
    end

    def clear_cache
      cache.clear
    end

    attr_accessor :cache_key
  end

  validates :name, presence: true

  def fts_employee
    @fts_employees ||= {}.compare_by_identity
    @fts_employee_id ||= {}.compare_by_identity

    @fts_employee_id[self] ||= id
    @fts_employees[self] ||= FtsEmployee.find(@fts_employee_id[self])
  end
end

# == Schema Information
#
# Table name: employees
#
#  id         :integer          not null, primary key
#  name       :string
#  position   :string
#  office     :string
#  age        :integer
#  start_date :date
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

app/controllers/employees_controller.rb
# frozen_string_literal: true

class EmployeesController < ApplicationController
  include SortableColumnsHelper
  include PagyHelper

  before_action :set_employee, except: %i[index new create]
  before_action :set_pagy_and_employees, only: :index

  # GET /employees or /employees.json
  def index
    render Employees::EmployeesIndexComponent.new(employees: @employees, pagy: @pagy).with_flash_content(@notice.to_s)
  end

  # GET /employees/1 or /employees/1.json
  def show
    respond_to do |format|
      format.json { render json: { employee: @employee.to_json, content: @employee.fts_employee.content.to_json } }
      format.html
    end
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # POST /employees or /employees.json
  def create
    company = Company.find(1)
    @employee = company.employees.create(employee_params)

    respond_to do |format|
      if @employee.safe_save
        set_employee_count

        format.turbo_stream
      else
        format.turbo_stream { render :create_failed }
      end
    end
  end

  # GET /employees/1/edit
  def edit; end

  # PATCH/PUT /employees/1/cancel_edit
  def cancel_edit
    respond_to do |format|
      format.json { render json: { employee: @employee.to_json, content: @employee.fts_employee.content.to_json } }
      format.turbo_stream
    end
  end

  # PATCH/PUT /employees/1 or /employees/1.json
  def update
    respond_to do |format|
      if @employee.safe_update(employee_params)
        format.turbo_stream
      else
        format.turbo_stream { render :edit }
      end
    end
  end

  # DELETE /employees/1 or /employees/1.json
  def destroy
    @employee.safe_destroy
    set_employee_count

    respond_to(&:turbo_stream)
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    params.require(:employee).permit(:name, :position, :office, :age, :start_date)
  end

  def set_employee_count
    @count = Employee.async_count
  end

  def set_pagy_and_employees
    @pagy, @employees = pagy_custom(
      Employee.build_search(params).reorder(
        sort_column(Employee) => sort_direction
      ),
      page: params.fetch(:page, 1),
      items: params.fetch(:count, 10),
      request_path: url_for(action: "index", controller: controller_name, only_path: true)
    )
  end
end

app/views/employees/_form.html.erb
<%= form_with model: @employee, class: "table-row", id: dom_id(@employee), data: { controller: "employee-form", employee_form_target: "form" } do |form| %>
  <div class="table-cell relative" data-label="name">
    <%= form.text_field :name %>
  </div>
  <div class="table-cell relative" data-label="position">
    <%= form.text_field :position %>
  </div>
  <div class="table-cell relative" data-label="office">
    <%= form.text_field :office %>
  </div>
  <div class="table-cell relative text-center" data-label="age">
    <%= form.number_field :age %>
  </div>
  <div class="table-cell relative text-center" data-label="start date">
    <%= form.date_field :start_date %>
  </div>
  <div class="table-cell new-employee">
    <div class="flex justify-around items-center">
      <%= form.submit "SAVE", class: "underline font-medium" %>
      <%= render Employees::EmployeeDeleteComponent.new(employee: @employee) %>
    </div>
  </div>
<% end %>

app/views/employees/cancel_edit.turbo_stream.erb
<%= turbo_stream.replace @employee do %>
  <%= render Employees::EmployeeTableRowComponent.new(employee: @employee) %>
<% end %>
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Editing of record ##{@employee.id} was successfully canceled.") %>
<% end %>

app/views/employees/create.turbo_stream.erb
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Employee record ##{@employee.id} was successfully created.") %>
<% end %>
<%= turbo_stream.remove "new_employee" %>
<turbo-stream action="prepend" target="employees" data-controller="pagy" data-pagy-total-value=<%= @count %> data-action="pagy#incrementTotal">
  <template>
    <%= render Employees::EmployeeTableRowComponent.new(employee: @employee) %>
  </template>
</turbo-stream>

app/views/employees/create_failed.turbo_stream.erb
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Failed to create new record. Fix errors #{@employee.errors.full_messages}, and resubmit employee.") %>
<% end %>
<%= turbo_stream.replace "new_employee" do %>
  <%= render Employees::EmployeeTableRowEditFormComponent.new(employee: @employee) %>
<% end %>

app/views/employees/destroy.turbo_stream.erb
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Employee record ##{@employee.id} was successfully deleted.") %>
<% end %>
<turbo-stream action="remove" target=<%= dom_id(@employee) %> data-controller="pagy" data-pagy-total-value=<%= @count %> data-action="pagy#decrementTotal"></turbo-stream>

app/views/employees/edit.html.erb
<%= render Employees::EmployeeTableRowEditFormComponent.new(employee: @employee) %>
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Editing record ##{@employee.id}.YEEHAA MUTHFACKA!!!") %>
<% end %>

app/views/employees/edit.turbo_stream.erb
<%= turbo_stream.replace @employee do %>
  <%= render Employees::EmployeeTableRowEditFormComponent.new(employee: @employee) %>
<% end %>
<%= turbo_stream.prepend "notices" do %>
  <% flash_message = (@employee.errors.any? ? "Editing record ##{@employee.id} failed." : "Editing record ##{@employee.id}.") %>
  <%= render FlashComponent.new(flash_notice: flash_message) %>
<% end %>

app/views/employees/edit_failed.turbo_stream.erb
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Failed to update new record. Fix errors #{@employee.errors.full_messages}, and resubmit changes.") %>
<% end %>
<%= turbo_stream.replace @employee do %>
  <%= render Employees::EmployeeTableRowEditFormComponent.new(employee: @employee) %>
<% end %>

app/views/employees/new.html.erb
<%= turbo_frame_tag "employees-table" do %>
  <%= render Employees::EmployeeTableRowFormComponent.new(employee: @employee) %>
<% end %>

app/views/employees/new.turbo_stream.erb
<%= turbo_stream.prepend "employees" do %>
  <%= render Employees::EmployeeTableRowEditFormComponent.new(employee: @employee) %>
<% end %>
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Creating new record.") %>
<% end %>

app/views/employees/show.html.erb
<div class="mycontainer">
  <%= render(DataTableComponent.new(model_data: Employee.where(id: @employee.id), width: 1200)) %>
  <div>
    <%= link_to "Back to employees", employees_path(extract_search_and_or_sort_params(params)) %>
  </div>
</div>

app/views/employees/update.turbo_stream.erb
<%= turbo_stream.replace @employee do %>
  <%= render Employees::EmployeeTableRowComponent.new(employee: @employee) %>
<% end %>
<%= turbo_stream.prepend "notices" do %>
  <%= render FlashComponent.new(flash_notice: "Employee record ##{@employee.id} was successfully updated.") %>
<% end %>