config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :employees do
    member do
      patch :cancel_edit
      post :edit
      post :new
    end
  end

  resources :sales, only: :index

  resource :dashboard, except: %i[index new create edit update destroy] do
    member do
      get :revenue
      get :orders
    end
  end

  root "employees#index"
end

app/models/sale.rb
# frozen_string_literal: true

class Sale < ApplicationRecord
  after_commit lambda {
    broadcast_update_to "revenue", partial: "metrics/revenue", locals: { data: Sale.total }, target: "revenue"
  }

  after_commit lambda {
    broadcast_update_to "orders", partial: "metrics/data", locals: { data: Sale.count }, target: "orders"
  }

  def self.total
    pluck(:amount).sum
  end
end

app/controllers/sales_controller.rb
# frozen_string_literal: true

class SalesController < ApplicationController
  def index
    @revenue = Sale.total || 0
  end
end

app/views/sales/index.html.erb
<div class="w-full flex flex-col gap-4 items-center justify-center">
  <h1>Demo Sales Admin Dashboard - showing how turbo stream channels work</h1>
  <div class="flex items-center justify-center gap-4 text-center">
    <%= button_to "Real-Time Revenue", revenue_dashboard_path, method: :get, data: { turbo_frame: "tab_data" }, class: "font-normal px-3 py-1 rounded-md text-cadetblue-50 bg-cadetblue-600" %>
    <%= button_to "Real-Time Orders", orders_dashboard_path, method: :get, data: { turbo_frame: "tab_data" }, class: "font-normal px-3 py-1 rounded-md text-cadetblue-50 bg-cadetblue-600" %>
  </div>
  <div class="text-center">
    <%= turbo_frame_tag "tab_data" do %>
      <%= turbo_stream_from "revenue" %>
      <div id="data">
        <%= render partial: "metrics/financial_data", locals: { data: @revenue } %>
      </div>
    <% end %>
  </div>
</div>